services:
  masonscarbroonline:
    build:
      context: .
      dockerfile: MasonScarbroOnline/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=PortfolioDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
      - Admin__PasswordHash=${ADMIN_PASSWORD_HASH}
      - Groq__Key=${GROQKEY} 
      - Github__Token=${GHTOKEN}
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}

    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata: